description: gan_mnist_pytorch_lightning_const
data:
  url: "https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz"
hyperparameters:
  global_batch_size: 64
  latent_dim: 100
  lr: 0.0002
  b1: 0.5
  b2: 0.999
searcher:
  name: single
  metric: opt_0_loss
  max_length:
    batches: 109
  smaller_is_better: True
entrypoint: model_def:GANTrial

max_restarts: 0
environment:
  image: ptl-cpu
