description: Ntsnet_Pytorch_const
hyperparameters:
 global_batch_size: 8
 dense1: 128
 data: /mnt/data
 arch: resnet18
 workers: 4
 start-epoch: 0
 lr: 0.1
 momentum: 0.9
 weight_decay: 1e-4
 pretrained: True
 
searcher:
 name: single
 metric: val_loss
 smaller_is_better: false
 max_length:
   batches: 50
entrypoint: model_def:MyTrial
max_restarts: 0
